# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  
  # config.vm.box = "gusztavvargadr/windows-10"
  config.vm.box = "gusztavvargadr/windows-server"
  
  config.vm.box_check_update = false

  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  config.vm.define "win-srv" do |machine|
    machine.vm.network "private_network", ip: "192.168.10.12"
  end

  config.vm.synced_folder "../.", "/vagrant_data"

    config.vm.provider "virtualbox" do |vb|
      vb.cpus=2
      vb.memory = "4096"
    end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "getPSversion.yaml"
    ansible.inventory_path = "inventory"
    ansible.verbose        = true
  end
  
end
