# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 
  config.vm.box = "ubuntu/trusty64"
    
  config.vm.define "server1" do |machine|
    machine.vm.network "private_network", ip: "192.168.10.11"
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = "1024"
    v.cpus = "1"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "install_docker.yaml"
    ansible.inventory_path = "inventory"
    ansible.verbose        = true
    ansible.limit          = "all" 
  end

end
